### PR TITLE
Latest 1.6.2914

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by jchannon** [comment]
Fixes #4

**Comment by sp0gg** [comment]
I don't do development on Windows any more. If you'd like access to update this package on Chocolatey, feel free to drop your Chocolatey username here and I will give it to you.

**Comment by jchannon** [comment]
I don't either, I'm trying to set up a windows dev machine for the odd occasion that i need to test something on windows 😄

**Comment by jchannon** [comment]
How do you publish the new versions?

**Comment by sp0gg** [comment]
First you need to set up an account and an API key on Chocolatey. Then you need to build the package using a command line tool. Then, once you have access to the repository (which I can grant you), you publish the package using the command line utility. It's been a while for me so it may have changed.

There might also be a way to automatically do these things, but I never got that deep into it.

https://github.com/chocolatey/choco/wiki/CreatePackages

**Comment by jchannon** [comment]
O'er!

Think I'll just wait for you to push the new package if that's ok :)

**Comment by sp0gg** [comment]
Well, you might be waiting for a while :cry:

**Comment by jchannon** [comment]
My chocolatey username is : jchannon

**Comment by jchannon** [comment]
@sp0gg am I good to go?

**Comment by sp0gg** [comment]
@jchannon I saw you posted your API key earlier, which is a security risk. I think you will want to revoke that and issue a new one (without posting it online). Once you've confirmed that you have done that, I will add you to the Chocolatey repo and you can publish the package.

**Comment by jchannon** [comment]
@sp0gg up did it as soon as i thought, hang on a minute i shouldn't have done that...

**Comment by sp0gg** [comment]
@jchannon I just added you as a maintainer. Feel free to modify the package in any way you see fit.

**Comment by jchannon** [comment]
New version pushed, thanks

**Pull request merged**
