### PR TITLE
Update to 1.7.3593

### PR DESCRIPTION
**Pull request by zotanmew**

### CODE REVIEW

**Comment by zotanmew** [comment]
The chocolatey package still isn't updated :(

**Comment by sp0gg** [comment]
Someone still needs to build it and upload it to the Chocolatey repo. If you post something on the Chocolatey site, hopefully one of the maintainers will see it and publish the package. :)

**Comment by gep13** [comment]
@sp0gg Are you not in a position to push the new package?  Are you no longer able to maintain this package?

**Comment by gep13** [comment]
@jchannon any chance you can push the latest version to chocolatey.org?

**Comment by sp0gg** [comment]
@gep13 No, I have not published a package to Chocolatey.org for over a year. I've added two maintainers for the package, but they don't appear to be active. I see you added ZotanWolf as well, and it looks like they published the new version. If you think it makes sense to remove all inactive maintainers, feel free to do so if that makes sense.

**Comment by gep13** [comment]
@sp0gg I see.  

After doing the merge of this PR, did you request that the other maintainers did the push?  If not, I am not sure how they would have known that a push was required?  Do the maintainers that were added to the Chocolatey Package have write access to this repository?  If not, I think that would help to allow them to maintain it.

**Comment by jchannon** [comment]
Based on #5 I think @sp0gg made me a maintainer of the chocolatey repo not the GH repo and after the PR was merged I could build and push to chocolatey

**Comment by sp0gg** [comment]
I added all maintainers and also @gep13 as collaborators to the repo.

**Comment by gep13** [comment]
@sp0gg that is great news!  Hopefully, between everyone here, we can keep this package up to date.

**Pull request merged**
